export const textProfile = {
    theme: "Theme",
    colorModeSystem: "System",
    colorModeLight: "Light",
    colorModeDark: "Dark",
    darkModeToggleLabel: "Dark mode toggle",
    darkMode: "Dark mode",
    friendsLabel: "Friends",
    noSharedReviews: "You haven't added any friends yet.",
    addFriendInputPlaceholder: "Enter a user's email address",
    showTutorial: "View tutorial",
    profile: "Profile",
    shareProfile: "Share profile",
    appearance: "Appearance",
    logOutConfirm: "Are you sure you want to log out?",
    memberSince: "Member since",
    reviewCountLabel: (count) => `${count} review${count === 1 ? "" : "s"}`,
    listCountLabel: (count) => `${count} list${count === 1 ? "" : "s"}`,
    featuredLists: "Featured Lists",
    settings: "Settings",
    selfFriendRequest: "You're already your own friend!",
    errorFailedRemoveFriend: "Failed to remove friend.",
    errorFailedCancelRequest: "Failed to cancel request.",
    friendRequestSent: "Friend request sent!",
    addFriend: "Add Friend",
    friendRequestLabel:
        "Send a friend request to people you want to share reviews with.",
};
