export const textLists = {
    createList: "Create List",
    listNameLabel: "Name",
    listNamePlaceholder: "e.g. Best Cafés",
    listDescriptionLabel: "Description (optional)",
    listDescriptionPlaceholder: "e.g. My favourite cafés in Auckland",
    listAddRestaurantsLabel: "Add restaurants",
    listAddRestaurantPlaceholder: "Add a restaurant...",
    restaurantCount: (count) =>
        `${count} ${count === 1 ? "restaurant" : "restaurants"}`,
    sharedWithCount: (count) => `${count} ${count === 1 ? "person" : "people"}`,
    canEdit: "Can edit",
    canView: "Can view",
    noLists: "You haven't created any lists yet. Tap + to get started.",
    shareList: "Share list",
    deleteList: "Delete list",
    leaveList: "Leave list",
    confirmDeleteList: "Delete this list?",
    confirmLeaveList: "Leave this list?",
    noRestaurantsEdit: "No restaurants yet. Search above to add one.",
    noRestaurantsView: "No restaurants on this list yet.",
    permissionLabel: "Permission",
    allFriendsShared: "All your friends already have access to this list.",
    noFriendsToShare: "Add friends first before sharing a list.",
    notSharedYet: "This list hasn't been shared with anyone yet.",
    listNoRestaurantsYet: "Search for restaurants to add them to your list.",
    addDescription: "Add description",
    owner: "Owner",
    checklistMode: "Checklist mode",
    checklistModeDescription: "Track which restaurants you've visited",
    check: "Mark as visited",
    uncheck: "Mark as not visited",
    checklistProgress: (checked, total) => `${checked}/${total} visited`,
    moveCheckedToBottom: "Move checked to bottom",
    shareViaLink: "Share via link",
    generateLink: "Generate link",
    revokeLink: "Revoke link",
    confirmRevokeLink: "Anyone with the link will lose access. Are you sure?",
    listNotFound: "List not found.",
    featureList: "Feature on profile",
    confirmRevokeFeatured:
        "This will also remove this list from your profile. Are you sure?",
    addManualRestaurant: (name) => `Add "${name}"`,
    addAddress: "Add address",
    addressPlaceholder: "Enter address",
    noFeaturedLists:
        "You haven't featured any lists yet. Feature a list to have it show up here.",
    showRatings: "Show ratings",
};
