export const textGlobal = {
    // General actions
    add: "Add",
    apply: "Apply",
    save: "Save",
    edit: "Edit",
    editLabel: (valueName) => `Edit ${valueName}`,
    remove: "Remove",
    removeLabel: (valueName) => `Remove ${valueName}`,
    delete: "Delete",
    cancel: "Cancel",
    close: "Close",
    done: "Done",
    submit: "Submit",
    saving: "Saving...",
    deleting: "Deleting...",
    sending: "Sending...",
    pending: "Pending",
    cancelling: "Canceling...",
    loading: "Loading...",
    uploading: "Uploading...",
    yes: "Yes",
    no: "No",
    next: "Next",
    back: "Back",
    gotIt: "Got it",
    show: "Show",
    hide: "Hide",
    to: "to",
    other: "other",
    accept: "Accept",
    decline: "Decline",
    dismiss: "Dismiss",
    send: "Send",
    share: "Share",
    copy: "Copy",
    generating: "Generating...",
    submitting: "Submitting...",
    restaurant: "restaurant",
    restaurants: "restaurants",

    // App
    appName1: "two",
    appName2: "top",
    reviews: "Reviews",
    lists: "Lists",

    // Auth
    logIn: "Log In",
    logOut: "Log Out",

    // Errors
    errorFormatted: (error) => `Error: ${error}`,
    errorPleaseTryAgain: "Please try again.",
    errorGeneric: "Something went wrong, please try again",
    errorMaxImages: "You can upload a maximum of 5 images",
    errorImageSize: "Images must be 20MB or less",
    invalidEmail: "Please enter a valid email address.",
    userNotFound: "User not found.",
    errorUserNameRequired: "Please enter a name.",
    errorUserNameTooLong: "Name must be less than 20 characters.",
    errorMissingRequiredFields: "Review notes or ratings are required.",

    // Time / Utils
    today: "Today",
    justNow: "Just now",
    minutesAgo: (n) => `${n}m ago`,
    hoursAgo: (n) => `${n}h ago`,
    daysAgo: (n) => `${n}d ago`,
};
