export const placeholders = [
    "Blend Café",
    "Boston Café",
    "Browne St",
    "Daily Bread",
    "Elixir Café",
    "Flying Burrito Brothers",
    "Honey Café",
    "Humbug",
    "Jam Organic Café",
    "Kokodak",
    "Lola",
    "Major Tom",
    "McCafé",
    "Mission Bay Café",
    "Rosebank Café & Kitchen",
    "Rude Boy",
    "Starbucks",
    "The Candy Shop",
    "The Federal Store",
    "The Garden Shed",
    "Tobi",
    "Twisted Tomato",
    "Winona Forever",
];

export const text = {
    appName: "MIMU",
    tagline: "Log in to view and write reviews",
    logIn: "Admin",
    logOut: "Log Out",
    writeReview: "Write a Review",
    close: "Close",
    submitReview: "Submit Review",
    submitting: "Submitting...",
    restaurantNameLabel: "Restaurant Name",
    restaurantNamePlaceholder: (name) => `e.g. ${name}`,
    dateVisitedLabel: "Date Visited",
    ratingsLabel: "Ratings",
    foodLabel: "Food",
    drinksLabel: "Drinks",
    ambienceLabel: "Ambience",
    reviewNotesLabel: "Review notes",
    reviewNotesPlaceholder: "Write your review here...",
    markAsPublic: "Mark as Public",

    loading: "Loading...",
    loadingReviews: "Loading reviews...",

    noReviews: "No reviews yet.",
    noPublicReviews: "No public reviews yet",
    errorFormatted: (error) => `Error: ${error}`,
    errorGeneric: "Something went wrong, please try again",
    errorFailedSubmit: "Failed to submit review.",
    errorFailedFetch: "Failed to fetch reviews.",
};
